[project]
name = "stock-trading-simulator"
version = "0.1.0"
description = "AI stock trading evaluation system"
dependencies = [
    "requests>=2.31.0",
    "pandas>=2.0.3",
    "numpy>=1.24.3",
    "matplotlib>=3.7.2",
    "alpha-vantage>=2.3.1"
]
requires-python = ">=3.8"